kind = "web"
previewPath = "/"
title = "Smart Energy & Saving System"
version = "1.0.0"
id = "artifacts/smart-energy"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23293

[services.development]
run = "pnpm --filter @workspace/smart-energy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/smart-energy", "run", "build" ]
publicDir = "artifacts/smart-energy/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23293"
BASE_PATH = "/"
